FROM mambaorg/micromamba:2.5.0

WORKDIR /app

COPY --chown=$MAMBA_USER:$MAMBA_USER environment.etl.docker.yml /tmp/environment.yml
RUN micromamba install -y -n base -f /tmp/environment.yml && \
    micromamba clean --all --yes

ARG MAMBA_DOCKERFILE_ACTIVATE=1
RUN pip install --no-cache-dir python-dotenv "psycopg[binary]"

COPY --chown=$MAMBA_USER:$MAMBA_USER . .

CMD ["micromamba","run","-n","base","python","-m","src.etl.run_all"]