FROM mambaorg/micromamba:1.5.8
WORKDIR /app

COPY environment.etl.docker.yml /tmp/environment.yml
RUN micromamba install -y -n base -f /tmp/environment.yml \
 && micromamba clean -a -y

COPY . .

CMD ["micromamba","run","-n","base","python","-m","src.etl.run_all"]